# Generated by Django 5.1.6 on 2025-02-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_rename_taskgroup_ingredient_recipeingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
